name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@main

      - name: Set up repository
        uses: actions/checkout@main
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Set up virtual display for TestFX (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-0 libnotify-bin libnss3 libxss1 libasound2

      - name: Start virtual display (Linux only)
        if: runner.os == 'Linux'
        run: Xvfb :99 -screen 0 1024x768x16 &
        env:
          DISPLAY: :99

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx

      # Run non-UI tests on Linux
      - name: Build and run non-UI tests on Linux
        run: ./gradlew check coverage
        if: matrix.platform == 'ubuntu-latest'  # Linux only runs non-UI tests

      # Run UI and non-UI tests on macOS and Windows
      - name: Build and run UI and non-UI tests on macOS and Windows
        run: ./gradlew check coverage -Dtestfx.headless=true
        if: matrix.platform == 'macos-latest' || matrix.platform == 'windows-latest'  # UI tests only on macOS/Windows

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
